source 'https://rubygems.org'
  gem 'activerecord', :require => 'active_record'
  gem 'bcrypt'
  gem 'chronic'
  gem 'rake'
  gem 'require_all'
  gem 'shotgun'
  gem 'sinatra'
  gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
  gem 'sqlite3'
  gem 'thin'
  gem "valid_email2"
